### ISSUE TITLE
`v1.5` documentation

### ISSUE THREAD

**Issue by vexy** [vexy/infoportal#1]
Update documentation for latest release.

**Comment by vexy** [comment]
Will be covered in `v2.0` documentation

**Comment by hupptechnologies** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
AmosInk, @douglasfsti, @walkskyer, @donchanee, @allendongyx, @ianmay139, @baiduwen3, @the-gc, @wundrellama, @sanjaynath, @obegendi, @sabotenwork, @justinmeiners, @francofabio, @newmys, @AustinJiangg, @Hell0wor1d, @slaninas, @JamesForan, @jayrmotta, @NenkaLab, @ArdeshirV, @sakthivelan-vijayakumar, @sohinisahukar, @hassoon1986, @metaver5o, @bobliugq, @zffgithub, @mktoho12, @weichang-x, @ahy231, @nabladev, @jpelaezClub, @RndPrecision, @zhouxinjing1, @TOSUKUi, @tsteinholz, @ioridev, @leechhui, @ianrtracey, @kanra0728, @bambi2016, @absognety, @mjc19930819, @donnielrt, @uty3714, @jiangtingdong, @Dyskovsky, @Lndngr, @brandon-foxVoxelot, @vserpokryl, @rayspock, @jungamer, @qtwtb, @bdnf, @shove70, @asilinwei, @fernandoAvargas, @chappjc, @KXwonderful, @rebornwwp, @A0dh, @lifa123, @kishore-ganesh, @ibhuang, @jxcpu2008, @endymio, @Ces-aq, @William0517, @gubareve, @yTpo1, @dakotagrvtt, @lydqc, @icecubewang, @illionhh, @stephenkgu, @ahmgeek, @ericm, @amuuu, @abakeola, @kimiakhpr, @tehribo, @shunkakinoki, @CorleoneH, @VFox700, @githubdzw, @Hanoso, @krasnojarskij, @fengshaoxie, @cfeng2013, @maijiahao, @psyashes, @danyduran, @shenghe, @sj3014, @thepushkarp, @dbaofd, @onoketa, @CodeStix
